"""Pydantic schemas for request / response validation and structured output."""

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Optional

from pydantic import AnyUrl, BaseModel, Field


# ── API Request / Response ──────────────────────────────────


class AnalyzeRequest(BaseModel):
    """POST /analyze payload."""

    url: AnyUrl = Field(..., description="Target application URL to analyse")
    prd_text: Optional[str] = Field(
        default=None,
        description="Product Requirements Document (PRD) text — auto-generated by Phase 0 if not provided",
    )
    run_mode: str = Field(
        default="auto",
        description="'auto' runs the full pipeline unattended; 'manual' pauses at each phase gate for human review",
    )
    prd_source: str = Field(
        default="reference",
        description="'own' — use prd_text as-is and skip Phase 0; 'reference' — research similar sites and auto-generate the PRD",
    )


class RunStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class AnalyzeResponse(BaseModel):
    """Response returned after a full or partial graph run."""

    thread_id: str
    status: RunStatus
    report: Optional[dict] = None
    errors: list[str] = Field(default_factory=list)


# ── Test Artefacts ──────────────────────────────────────────


class TestStep(BaseModel):
    step_number: int
    action: str
    expected_result: str


class Severity(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class TestCase(BaseModel):
    id: str
    feature: str
    scenario: str
    steps: list[TestStep]
    expected_result: str
    severity: Severity = Severity.MEDIUM
    tags: list[str] = Field(default_factory=list)


class BugReport(BaseModel):
    title: str
    severity: Severity
    steps_to_reproduce: list[str]
    expected_behaviour: str
    actual_behaviour: str
    screenshot_path: Optional[str] = None
    environment: Optional[str] = None


# ── Multi-POV Report ────────────────────────────────────────


class POVReport(BaseModel):
    """Reports generated for different audiences."""

    stakeholder: str = Field(
        ..., description="Business-value perspective for stakeholders"
    )
    developer: str = Field(
        ..., description="Technical-debt & implementation perspective"
    )
    user: str = Field(..., description="UX friction & usability perspective")


# ── HITL Resume ─────────────────────────────────────────────


class ResumeRequest(BaseModel):
    """POST /runs/{thread_id}/resume payload."""

    phase: int = Field(
        ...,
        ge=0,
        le=4,
        description="Which phase gate to approve/reject (0–4)",
    )
    approved: bool = Field(
        ...,
        description="True to proceed to next phase; False to route back to the phase's LLM generator",
    )
    feedback: str = Field(
        default="",
        description="Optional human comment appended to state['human_feedback']",
    )
    edited_state_payload: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional dict of state fields to overwrite (e.g. {'test_cases': [...]})",
    )
