"""LangGraph state definition for the QA-Web-Agent V2 workflow."""

from __future__ import annotations

from operator import add
from typing import Annotated, Literal, Optional

from typing_extensions import TypedDict


class QAState(TypedDict, total=False):
    """
    Stateful context passed through every LangGraph node.

    Annotated fields with `add` use an append-reducer —
    new values are *appended* rather than replaced.

    Plain list fields (no Annotated) are overwrite-reducers —
    the last write wins, enabling humans to fully replace them
    via the HITL resume API.
    """

    # ── Inputs ──────────────────────────────────────────────
    url: str
    project_description: str  # PRD text — auto-generated by Phase 0 if not provided

    # ── Phase 0: PRD Maker ──────────────────────────────────
    prd_site_type: Optional[str]         # detected category (portfolio, e-commerce, …)
    prd_site_description: Optional[str]  # one-line description of the site type
    prd_references: Optional[list[dict]] # [{url, content}, …] — 4 fetched reference sites

    # ── Run control ─────────────────────────────────────────
    run_mode: Literal["auto", "manual"]  # "auto" skips all HITL gates
    prd_source: Literal["own", "reference"]  # "own" skips Phase 0 (research + draft)

    # ── Phase 1: Contextual Intelligence ────────────────────
    raw_dom: Optional[str]
    page_analysis: Optional[str]      # unified DOM summary from DOMProcessor
    technical_overview: Optional[dict]  # product knowledge graph

    # ── Phase 2: QA Documentation ───────────────────────────
    # Plain list — humans can completely overwrite via /resume API
    test_cases: list[dict]
    # Intermediate sub-outputs for Strategist cluster
    happy_path_cases: Optional[list[dict]]
    edge_case_cases: Optional[list[dict]]

    # ── Cypress Docs Check (between Phase 1 and Phase 2) ────
    cypress_api_context: Optional[dict]  # live-fetched Cypress API context from docs subgraph

    # ── Phase 3: Automation ─────────────────────────────────
    cypress_code: Optional[str]              # summary / manifest of generated files
    cypress_file_paths: Annotated[list[str], add]  # paths to .cy.js and report files
    lint_errors: Optional[list[str]]         # spec syntax/lint errors from syntax_linter
    pom_lint_errors: Optional[list[str]]     # POM syntax errors from syntax_linter
    lint_retry_count: int                    # shared budget for both lint retry loops

    # ── Phase 5: Reporter ───────────────────────────────────
    report_paths: Optional[list[str]]   # absolute paths to written .md files
    report_summary: Optional[dict]      # {pass_rate, total_tests, app_bugs, report_files}

    # ── Execution & Self-Healing ────────────────────────────
    errors: Annotated[list[str], add]
    execution_history: Annotated[list[dict], add]
    retry_count: int                         # legacy V1 counter (backward compat)
    classified_errors: Annotated[list[dict], add]  # {type: "test_code_error"|"app_bug", message: str}
    heal_retry_count: int                    # governs heal_tests → run_cypress loop

    # ── Human-in-the-Loop (HITL) ────────────────────────────
    human_feedback: Annotated[list[str], add]  # append-only audit trail
    phase_0_approved: bool   # PRD review gate (mandatory — always pauses)
    phase_1_approved: bool
    phase_2_approved: bool
    phase_3_approved: bool
    phase_4_approved: bool


class CypressDocsState(TypedDict, total=False):
    """Internal state for the cypress_docs subgraph.
    Only `cypress_api_context` is written back to the parent QAState.
    """
    docs_raw: dict              # {page_name: cleaned_text}
    api_changes: list           # [{command, change_type, detail}]
    rules_addendum: str         # extra rules string from LLM analysis
    cypress_api_context: dict   # final output — merged into parent state
